version: '3.8'

services:
  postgresdb-todo:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    container_name: pg-blog
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blogpost
    volumes:
      - blog-pgdata:/var/lib/postgresql/data

volumes:
  blog-pgdata:
